export const metatag = (pageTitle, pageUrl, robots, keywords = []) => {
  const fav = "https://cli.pras.me/favicon/favicon-512x512.png";

  const fixedKeywords = [
    "PRAS",
    "PRAS CLI",
    "PRAS Samin",
    "PRASSamin",
    "CLI",
    "Command-line",
    "Terminal",
    "Tool",
    "Automation",
    "Developer",
    "Python",
    "Interface",
    "Guide",
    "Documentation",
    "Scripting",
    "Workflow",
    "Productivity",
    "Utilities",
    "Open-source",
    "Cross-platform",
    "Efficient",
    "Custom",
    "Simplify",
    "Speed",
    "Tasks",
    "Commands",
    "Scripts",
    "Lightweight",
    "Powerful",
    "Tools",
    "Developers",
    "Command-line interface",
    "CLI guide",
    "Terminal productivity",
    "Workflow automation",
    "Custom CLI solutions",
    "CLI documentation",
    "Command-line documentation",
    "Terminal automation",
    "Developer CLI tools",
    "CLI for developers",
    "Command-line tools for developers",
    "Developer productivity tools",
    "Command-line scripting",
    "Python CLI",
    "Python-based tools",
    "Cross-platform CLI",
    "Open-source CLI tools",
    "CLI tools for automation",
    "Efficient command-line tools",
    "CLI for workflow automation",
    "Terminal utilities",
    "Custom CLI solutions",
    "Lightweight CLI tools",
    "Simplify command-line tasks",
    "Speed up developer workflows",
    "Automate repetitive tasks",
    "Boost terminal productivity",
  ];

  const margedkeywords = fixedKeywords.concat(keywords);

  return {
    title: pageTitle,
    canonical: pageUrl,
    keywords: margedkeywords,
    openGraph: {
      title: pageTitle,
      url: pageUrl,
      siteName: pageTitle,
      images: [
        {
          url: fav,
          width: 1200,
          height: 630,
        },
      ],
      locale: "en_US",
      type: "website",
    },
    twitter: {
      title: pageTitle,
      creator: "@prassamin78",
      images: [fav],
    },
    alternates: {
      canonical: pageUrl,
      languages: { "en-US": pageUrl },
    },
    robots: robots,
    structuredData: {
      name: pageTitle,
      url: pageUrl,
    },
  };
};
